mesh1:
	netgen -geofile=pyramid_shell1.geo -meshfiletype="Neutral Format" -meshfile=pyramid_shell1.neutral -batchmode
	nmeshimport --netgen pyramid_shell1.neutral pyramid_shell1.nmesh.h5

mesh2:
	netgen -geofile=pyramid_shell2.geo -meshfiletype="Neutral Format" -meshfile=pyramid_shell2.neutral -batchmode
	nmeshimport --netgen pyramid_shell2.neutral pyramid_shell2.nmesh.h5

mesh3:
	netgen -geofile=pyramid_shell3.geo -meshfiletype="Neutral Format" -meshfile=pyramid_shell3.neutral -batchmode
	nmeshimport --netgen pyramid_shell3.neutral pyramid_shell3.nmesh.h5

mesh4:
	netgen -geofile=pyramid_shell4.geo -meshfiletype="Neutral Format" -meshfile=pyramid_shell4.neutral -batchmode
	nmeshimport --netgen pyramid_shell4.neutral pyramid_shell4.nmesh.h5

mesh5:
	netgen -geofile=pyramid_shell5.geo -meshfiletype="Neutral Format" -meshfile=pyramid_shell5.neutral -batchmode
	nmeshimport --netgen pyramid_shell5.neutral pyramid_shell5.nmesh.h5

mesh6:
	netgen -geofile=pyramid_shell6.geo -meshfiletype="Neutral Format" -meshfile=pyramid_shell6.neutral -batchmode
	nmeshimport --netgen pyramid_shell6.neutral pyramid_shell6.nmesh.h5

mesh7:
	netgen -geofile=pyramid_shell7.geo -meshfiletype="Neutral Format" -meshfile=pyramid_shell7.neutral -batchmode
	nmeshimport --netgen pyramid_shell7.neutral pyramid_shell7.nmesh.h5


